# Generated by Django 4.2 on 2025-05-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_test_alter_assessment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
